from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from se.krka.kahlua.vm import KahluaTable
from zombie.gameStates import GameState, GameStateMachine

class WorldMapEditorState(GameState):

  instance: WorldMapEditorState

  def enter(self) -> None: ...

  def exit(self) -> None: ...

  def fromLua0(self, func: str) -> object: ...

  def load(self) -> None: ...

  def reenter(self) -> None: ...

  def render(self) -> None: ...

  def save(self) -> None: ...

  def setTable(self, table: KahluaTable) -> None: ...

  def update(self) -> GameStateMachine.StateAction: ...

  @staticmethod
  def checkInstance() -> WorldMapEditorState: ...

  def __init__(self): ...

