from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from zombie.Lua import LuaManager
from zombie.util import PooledObject
from zombie.worldMap import UIWorldMap

class WorldMapGridSquareMarker(WorldMapMarker):

  def setBlink(self, blink: bool) -> None: ...

  def setMinScreenRadius(self, pixels: int) -> None: ...

  def __init__(self): ...


class WorldMapMarker(PooledObject):

  def __init__(self): ...


class WorldMapMarkers:

  def addGridSquareMarker(self, worldX: int, worldY: int, radius: int, r: float, g: float, b: float, a: float) -> WorldMapGridSquareMarker: ...

  def clear(self) -> None: ...

  def removeMarker(self, marker: WorldMapMarker) -> None: ...

  def render(self, ui: UIWorldMap) -> None: ...

  def __init__(self): ...


class WorldMapMarkersV1:

  def addGridSquareMarker(self, worldX: int, worldY: int, radius: int, r: float, g: float, b: float, a: float) -> WorldMapMarkersV1.WorldMapGridSquareMarkerV1: ...

  def clear(self) -> None: ...

  def removeMarker(self, marker: WorldMapMarkersV1.WorldMapMarkerV1) -> None: ...

  @staticmethod
  def setExposed(exposer: LuaManager.Exposer) -> None: ...

  def __init__(self, ui: UIWorldMap): ...

  class WorldMapGridSquareMarkerV1(WorldMapMarkersV1.WorldMapMarkerV1):

    def setBlink(self, blink: bool) -> None: ...

    def setMinScreenRadius(self, pixels: int) -> None: ...

  class WorldMapMarkerV1: ...

