from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.util import Iterator

class NamespaceContext:

  def getNamespaceURI(self, arg0: str) -> str: ...

  def getPrefix(self, arg0: str) -> str: ...

  def getPrefixes(self, arg0: str) -> Iterator[str]: ...


class QName:

  def equals(self, arg0: object) -> bool: ...

  def getLocalPart(self) -> str: ...

  def getNamespaceURI(self) -> str: ...

  def getPrefix(self) -> str: ...

  def hashCode(self) -> int: ...

  def toString(self) -> str: ...

  @staticmethod
  def valueOf(arg0: str) -> QName: ...

  @overload
  def __init__(self, arg0: str): ...
  @overload
  def __init__(self, arg0: str, arg1: str): ...
  @overload
  def __init__(self, arg0: str, arg1: str, arg2: str): ...

