from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from javax.xml.transform import Source, Result
from org.w3c.dom import TypeInfo
from org.w3c.dom.ls import LSResourceResolver
from org.xml.sax import ErrorHandler, ContentHandler, Locator, Attributes

class Schema:

  def newValidator(self) -> Validator: ...

  def newValidatorHandler(self) -> ValidatorHandler: ...


class TypeInfoProvider:

  def getAttributeTypeInfo(self, arg0: int) -> TypeInfo: ...

  def getElementTypeInfo(self) -> TypeInfo: ...

  def isIdAttribute(self, arg0: int) -> bool: ...

  def isSpecified(self, arg0: int) -> bool: ...


class Validator:

  def getErrorHandler(self) -> ErrorHandler: ...

  def getFeature(self, arg0: str) -> bool: ...

  def getProperty(self, arg0: str) -> object: ...

  def getResourceResolver(self) -> LSResourceResolver: ...

  def reset(self) -> None: ...

  def setErrorHandler(self, arg0: ErrorHandler) -> None: ...

  def setFeature(self, arg0: str, arg1: bool) -> None: ...

  def setProperty(self, arg0: str, arg1: object) -> None: ...

  def setResourceResolver(self, arg0: LSResourceResolver) -> None: ...

  @overload
  def validate(self, arg0: Source) -> None: ...

  @overload
  def validate(self, arg0: Source, arg1: Result) -> None: ...


class ValidatorHandler:

  def characters(self, arg0: list[str], arg1: int, arg2: int) -> None: ...

  def declaration(self, arg0: str, arg1: str, arg2: str) -> None: ...

  def endDocument(self) -> None: ...

  def endElement(self, arg0: str, arg1: str, arg2: str) -> None: ...

  def endPrefixMapping(self, arg0: str) -> None: ...

  def getContentHandler(self) -> ContentHandler: ...

  def getErrorHandler(self) -> ErrorHandler: ...

  def getFeature(self, arg0: str) -> bool: ...

  def getProperty(self, arg0: str) -> object: ...

  def getResourceResolver(self) -> LSResourceResolver: ...

  def getTypeInfoProvider(self) -> TypeInfoProvider: ...

  def ignorableWhitespace(self, arg0: list[str], arg1: int, arg2: int) -> None: ...

  def processingInstruction(self, arg0: str, arg1: str) -> None: ...

  def setContentHandler(self, arg0: ContentHandler) -> None: ...

  def setDocumentLocator(self, arg0: Locator) -> None: ...

  def setErrorHandler(self, arg0: ErrorHandler) -> None: ...

  def setFeature(self, arg0: str, arg1: bool) -> None: ...

  def setProperty(self, arg0: str, arg1: object) -> None: ...

  def setResourceResolver(self, arg0: LSResourceResolver) -> None: ...

  def skippedEntity(self, arg0: str) -> None: ...

  def startDocument(self) -> None: ...

  def startElement(self, arg0: str, arg1: str, arg2: str, arg3: Attributes) -> None: ...

  def startPrefixMapping(self, arg0: str, arg1: str) -> None: ...

