from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation

class Display:

  @staticmethod
  def display(v: int) -> str: ...

  def __init__(self): ...


class Exceptions:

  @staticmethod
  def cannotAdapt(name: str) -> None: ...

  @staticmethod
  def cannotMergeRanges(r1: object, r2: object) -> None: ...

  @staticmethod
  def cloning() -> None: ...

  @staticmethod
  def dequeNoFirst() -> None: ...

  @staticmethod
  def dequeNoFirstToRemove() -> None: ...

  @staticmethod
  def dequeNoLast() -> None: ...

  @staticmethod
  def dequeNoLastToRemove() -> None: ...

  @staticmethod
  def endOfIterator() -> None: ...

  @staticmethod
  def indexOutOfBounds(index: int, low: int, high: int) -> None: ...

  @staticmethod
  def invalidLowerBound(value: object) -> None: ...

  @staticmethod
  def invalidRangeBounds(first: object, last: object) -> None: ...

  @staticmethod
  def invalidSetBounds(low: object, high: object) -> None: ...

  @staticmethod
  def invalidUpperBound(value: object) -> None: ...

  @staticmethod
  def negativeArgument(name: str, value: object) -> None: ...

  @staticmethod
  def negativeOrZeroArgument(name: str, value: object) -> None: ...

  @staticmethod
  def noElementToGet() -> None: ...

  @staticmethod
  def noElementToRemove() -> None: ...

  @staticmethod
  def noElementToSet() -> None: ...

  @staticmethod
  def noLastElement() -> None: ...

  @staticmethod
  def noSuchMapping(key: object) -> None: ...

  @staticmethod
  def nullArgument(name: str) -> None: ...

  @staticmethod
  def nullElementNotAllowed() -> None: ...

  @staticmethod
  def setNoFirst() -> None: ...

  @staticmethod
  def setNoLast() -> None: ...

  @staticmethod
  def startOfIterator() -> None: ...

  @staticmethod
  def unmodifiable(name: str) -> None: ...

  @staticmethod
  def unsupported(name: str) -> None: ...

  @staticmethod
  def valueNotInSubRange(value: object) -> None: ...

  def __init__(self): ...

