from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation

class SecretKeySpec:

  serialVersionUID: int

  def equals(self, arg0: object) -> bool: ...

  def getAlgorithm(self) -> str: ...

  def getEncoded(self) -> list[int]: ...

  def getFormat(self) -> str: ...

  def hashCode(self) -> int: ...

  @overload
  def __init__(self, arg0: list[int], arg1: str): ...
  @overload
  def __init__(self, arg0: list[int], arg1: int, arg2: int, arg3: str): ...

