from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.io import OutputStream, File
from java.util import Date

class ArchiveEntry:

  SIZE_UNKNOWN: int

  def getLastModifiedDate(self) -> Date: ...

  def getName(self) -> str: ...

  def getSize(self) -> int: ...

  def isDirectory(self) -> bool: ...


class ArchiveOutputStream(OutputStream):

  def canWriteEntryData(self, arg0: ArchiveEntry) -> bool: ...

  def closeArchiveEntry(self) -> None: ...

  def createArchiveEntry(self, arg0: File, arg1: str) -> ArchiveEntry: ...

  def finish(self) -> None: ...

  def getBytesWritten(self) -> int: ...

  def getCount(self) -> int: ...

  def putArchiveEntry(self, arg0: ArchiveEntry) -> None: ...

  def write(self, arg0: int) -> None: ...

  def __init__(self): ...

