from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.io import InputStream, OutputStream
from java.util import List
from java.util.jar import JarFile

class JarIndex:

  INDEX_NAME: str

  def add(self, arg0: str, arg1: str) -> None: ...

  def get(self, arg0: str) -> List[str]: ...

  def getJarFiles(self) -> list[str]: ...

  def merge(self, arg0: JarIndex, arg1: str) -> None: ...

  def read(self, arg0: InputStream) -> None: ...

  def write(self, arg0: OutputStream) -> None: ...

  @staticmethod
  def getJarIndex(arg0: JarFile) -> JarIndex: ...

  @overload
  def __init__(self): ...
  @overload
  def __init__(self, arg0: list[str]): ...
  @overload
  def __init__(self, arg0: InputStream): ...

