from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.awt import Color
from org.json import JSONObject

class EmbedBuilder:

  def addField(self, arg0: str, arg1: str, arg2: bool) -> EmbedBuilder: ...

  @overload
  def setAuthor(self, arg0: str) -> EmbedBuilder: ...

  @overload
  def setAuthor(self, arg0: str, arg1: str, arg2: str) -> EmbedBuilder: ...

  def setColor(self, arg0: Color) -> EmbedBuilder: ...

  def setDescription(self, arg0: str) -> EmbedBuilder: ...

  @overload
  def setFooter(self, arg0: str) -> EmbedBuilder: ...

  @overload
  def setFooter(self, arg0: str, arg1: str) -> EmbedBuilder: ...

  def setImage(self, arg0: str) -> EmbedBuilder: ...

  def setThumbnail(self, arg0: str) -> EmbedBuilder: ...

  def setTitle(self, arg0: str) -> EmbedBuilder: ...

  def setUrl(self, arg0: str) -> EmbedBuilder: ...

  def toJSONObject(self) -> JSONObject: ...

  def __init__(self): ...

