from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from org.lwjglx.input import Controller

class Input:

  ANY_CONTROLLER: int

  def getAxisCount(self, index: int) -> int: ...

  def getAxisName(self, index: int, axis: int) -> str: ...

  def getAxisValue(self, index: int, axis: int) -> float: ...

  def getButtonCount(self, index: int) -> int: ...

  def getButtonName(self, index: int, button: int) -> str: ...

  def getController(self, index: int) -> Controller: ...

  def getControllerCount(self) -> int: ...

  def initControllers(self) -> None: ...

  def isButtonPressedD(self, button: int, index: int) -> bool: ...

  def isButtonReleasePress(self, index: int, button: int) -> bool: ...

  def isButtonStartPress(self, index: int, button: int) -> bool: ...

  def isControllerDownD(self, index: int) -> bool: ...

  def isControllerLeftD(self, index: int) -> bool: ...

  def isControllerRightD(self, index: int) -> bool: ...

  def isControllerUpD(self, index: int) -> bool: ...

  def poll(self) -> None: ...

  def quit(self) -> None: ...

  def updateGameThread(self) -> None: ...

  def wasButtonPressed(self, index: int, button: int) -> bool: ...

  @staticmethod
  def getKeyCode(keyName: str) -> int: ...

  @staticmethod
  def getKeyName(code: int) -> str: ...

  def __init__(self): ...

