from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation

class Noise2D:

  def addLayer(self, _seed: int, _freq: float, _amp: float) -> None: ...

  def layeredNoise(self, _x: float, _y: float) -> float: ...

  def reset(self) -> None: ...

  def __init__(self): ...

  class Layer: ...

