from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from gnu.trove.stack import TIntStack
from java.io import ObjectInput, ObjectOutput

class TIntArrayStack:

  DEFAULT_CAPACITY: int

  @overload
  def clear(self) -> None: ...

  @overload
  def clear(self) -> None: ...

  def equals(self, arg0: object) -> bool: ...

  @overload
  def getNoEntryValue(self) -> int: ...

  @overload
  def getNoEntryValue(self) -> int: ...

  def hashCode(self) -> int: ...

  @overload
  def peek(self) -> int: ...

  @overload
  def peek(self) -> int: ...

  @overload
  def pop(self) -> int: ...

  @overload
  def pop(self) -> int: ...

  @overload
  def push(self, arg0: int) -> None: ...

  @overload
  def push(self, arg0: int) -> None: ...

  @overload
  def readExternal(self, arg0: ObjectInput) -> None: ...

  @overload
  def readExternal(self, arg0: ObjectInput) -> None: ...

  @overload
  def size(self) -> int: ...

  @overload
  def size(self) -> int: ...

  @overload
  def toArray(self) -> list[int]: ...

  @overload
  def toArray(self) -> list[int]: ...

  @overload
  def toArray(self, arg0: list[int]) -> None: ...

  @overload
  def toArray(self, arg0: list[int]) -> None: ...

  def toString(self) -> str: ...

  @overload
  def writeExternal(self, arg0: ObjectOutput) -> None: ...

  @overload
  def writeExternal(self, arg0: ObjectOutput) -> None: ...

  @overload
  def __init__(self): ...
  @overload
  def __init__(self, arg0: TIntStack): ...
  @overload
  def __init__(self, arg0: int): ...
  @overload
  def __init__(self, arg0: int, arg1: int): ...

