from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.awt import Component, Dimension, Graphics
from java.awt.event import MouseEvent
from javax.accessibility import Accessible
from javax.swing import JComponent, JPopupMenu, Popup

class ButtonUI(ComponentUI): ...


class ComponentUI:

  def contains(self, arg0: JComponent, arg1: int, arg2: int) -> bool: ...

  def getAccessibleChild(self, arg0: JComponent, arg1: int) -> Accessible: ...

  def getAccessibleChildrenCount(self, arg0: JComponent) -> int: ...

  def getBaseline(self, arg0: JComponent, arg1: int, arg2: int) -> int: ...

  def getBaselineResizeBehavior(self, arg0: JComponent) -> Component.BaselineResizeBehavior: ...

  def getMaximumSize(self, arg0: JComponent) -> Dimension: ...

  def getMinimumSize(self, arg0: JComponent) -> Dimension: ...

  def getPreferredSize(self, arg0: JComponent) -> Dimension: ...

  def installUI(self, arg0: JComponent) -> None: ...

  def paint(self, arg0: Graphics, arg1: JComponent) -> None: ...

  def uninstallUI(self, arg0: JComponent) -> None: ...

  def update(self, arg0: Graphics, arg1: JComponent) -> None: ...

  @staticmethod
  def createUI(arg0: JComponent) -> ComponentUI: ...

  def __init__(self): ...


class MenuBarUI(ComponentUI): ...


class MenuItemUI(ButtonUI): ...


class PanelUI(ComponentUI): ...


class PopupMenuUI(ComponentUI):

  def getPopup(self, arg0: JPopupMenu, arg1: int, arg2: int) -> Popup: ...

  def isPopupTrigger(self, arg0: MouseEvent) -> bool: ...


class RootPaneUI(ComponentUI): ...


class SeparatorUI(ComponentUI): ...


class ToolTipUI(ComponentUI): ...

