from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.util import Enumeration

class AttributeSet:

  NameAttribute: object

  ResolveAttribute: object

  def containsAttribute(self, arg0: object, arg1: object) -> bool: ...

  def containsAttributes(self, arg0: AttributeSet) -> bool: ...

  def copyAttributes(self) -> AttributeSet: ...

  def getAttribute(self, arg0: object) -> object: ...

  def getAttributeCount(self) -> int: ...

  def getAttributeNames(self) -> Enumeration[Any]: ...

  def getResolveParent(self) -> AttributeSet: ...

  def isDefined(self, arg0: object) -> bool: ...

  def isEqual(self, arg0: AttributeSet) -> bool: ...

  class ParagraphAttribute: ...

  class CharacterAttribute: ...

  class ColorAttribute: ...

  class FontAttribute: ...

