from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.io import InputStream, Reader

class LSInput:

  def getBaseURI(self) -> str: ...

  def getByteStream(self) -> InputStream: ...

  def getCertifiedText(self) -> bool: ...

  def getCharacterStream(self) -> Reader: ...

  def getEncoding(self) -> str: ...

  def getPublicId(self) -> str: ...

  def getStringData(self) -> str: ...

  def getSystemId(self) -> str: ...

  def setBaseURI(self, arg0: str) -> None: ...

  def setByteStream(self, arg0: InputStream) -> None: ...

  def setCertifiedText(self, arg0: bool) -> None: ...

  def setCharacterStream(self, arg0: Reader) -> None: ...

  def setEncoding(self, arg0: str) -> None: ...

  def setPublicId(self, arg0: str) -> None: ...

  def setStringData(self, arg0: str) -> None: ...

  def setSystemId(self, arg0: str) -> None: ...


class LSResourceResolver:

  def resolveResource(self, arg0: str, arg1: str, arg2: str, arg3: str, arg4: str) -> LSInput: ...

