from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.io import PrintStream
from se.krka.kahlua.vm import KahluaThread, KahluaTable, Platform

class BlockingKahluaThread(KahluaThread):

  @overload
  def call(self, arg0: int) -> int: ...

  @overload
  def call(self, arg0: object, arg1: list[object]) -> object: ...

  @overload
  def call(self, arg0: object, arg1: object, arg2: object, arg3: object) -> object: ...

  def getEnvironment(self) -> KahluaTable: ...

  def getMetaOp(self, arg0: object, arg1: str) -> object: ...

  def getmetatable(self, arg0: object, arg1: bool) -> object: ...

  @overload
  def pcall(self, arg0: int) -> int: ...

  @overload
  def pcall(self, arg0: object) -> list[object]: ...

  @overload
  def pcall(self, arg0: object, arg1: list[object]) -> list[object]: ...

  def setmetatable(self, arg0: object, arg1: KahluaTable) -> None: ...

  def tableSet(self, arg0: object, arg1: object, arg2: object) -> None: ...

  def tableget(self, arg0: object, arg1: object) -> object: ...

  @staticmethod
  def main(arg0: list[str]) -> None: ...

  @overload
  def __init__(self, arg0: Platform, arg1: KahluaTable): ...
  @overload
  def __init__(self, arg0: PrintStream, arg1: Platform, arg2: KahluaTable): ...


class VerifiedSingleKahluaThread(KahluaThread):

  @overload
  def call(self, arg0: int) -> int: ...

  @overload
  def call(self, arg0: object, arg1: list[object]) -> object: ...

  @overload
  def call(self, arg0: object, arg1: object, arg2: object, arg3: object) -> object: ...

  def getEnvironment(self) -> KahluaTable: ...

  def getMetaOp(self, arg0: object, arg1: str) -> object: ...

  def getmetatable(self, arg0: object, arg1: bool) -> object: ...

  @overload
  def pcall(self, arg0: int) -> int: ...

  @overload
  def pcall(self, arg0: object) -> list[object]: ...

  @overload
  def pcall(self, arg0: object, arg1: list[object]) -> list[object]: ...

  def setmetatable(self, arg0: object, arg1: KahluaTable) -> None: ...

  def tableSet(self, arg0: object, arg1: object, arg2: object) -> None: ...

  def tableget(self, arg0: object, arg1: object) -> object: ...

  @overload
  def __init__(self, arg0: Platform, arg1: KahluaTable): ...
  @overload
  def __init__(self, arg0: PrintStream, arg1: Platform, arg2: KahluaTable): ...

