from typing import Any, overload, TypeVar
from java.lang.annotation import Annotation
from java.awt import BufferCapabilities, Image, Font, FontMetrics, Graphics, GraphicsConfiguration, Point, Dimension, AWTEvent, Component, Color, CheckboxGroup, Insets, Desktop, Window, Dialog, Rectangle, MenuBar, Menu, MenuItem, Event, Adjustable, PopupMenu, Taskbar
from java.awt.desktop import SystemEventListener, AboutHandler, OpenFilesHandler, OpenURIHandler, PreferencesHandler, PrintFilesHandler, QuitHandler, QuitStrategy
from java.awt.event import PaintEvent, FocusEvent
from java.awt.im import InputMethodRequests
from java.awt.image import VolatileImage, ColorModel
from java.io import File, FilenameFilter
from java.net import URI
from java.util import List
from javax.swing import JMenuBar
from sun.java2d.pipe import Region

class ButtonPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setLabel(self, arg0: str) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class CanvasPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getAppropriateGraphicsConfiguration(self, arg0: GraphicsConfiguration) -> GraphicsConfiguration: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class CheckboxMenuItemPeer:

  def setEnabled(self, arg0: bool) -> None: ...

  def setLabel(self, arg0: str) -> None: ...

  def setState(self, arg0: bool) -> None: ...


class CheckboxPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setCheckboxGroup(self, arg0: CheckboxGroup) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setLabel(self, arg0: str) -> None: ...

  def setState(self, arg0: bool) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class ChoicePeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def add(self, arg0: str, arg1: int) -> None: ...

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def remove(self, arg0: int) -> None: ...

  def removeAll(self) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def select(self, arg0: int) -> None: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class ComponentPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class ContainerPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def beginLayout(self) -> None: ...

  def beginValidate(self) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def endLayout(self) -> None: ...

  def endValidate(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getInsets(self) -> Insets: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class DesktopPeer:

  def addAppEventListener(self, arg0: SystemEventListener) -> None: ...

  def browse(self, arg0: URI) -> None: ...

  def browseFileDirectory(self, arg0: File) -> bool: ...

  def disableSuddenTermination(self) -> None: ...

  def edit(self, arg0: File) -> None: ...

  def enableSuddenTermination(self) -> None: ...

  def isSupported(self, arg0: Desktop.Action) -> bool: ...

  def mail(self, arg0: URI) -> None: ...

  def moveToTrash(self, arg0: File) -> bool: ...

  def open(self, arg0: File) -> None: ...

  def openHelpViewer(self) -> None: ...

  def print(self, arg0: File) -> None: ...

  def removeAppEventListener(self, arg0: SystemEventListener) -> None: ...

  def requestForeground(self, arg0: bool) -> None: ...

  def setAboutHandler(self, arg0: AboutHandler) -> None: ...

  def setDefaultMenuBar(self, arg0: JMenuBar) -> None: ...

  def setOpenFileHandler(self, arg0: OpenFilesHandler) -> None: ...

  def setOpenURIHandler(self, arg0: OpenURIHandler) -> None: ...

  def setPreferencesHandler(self, arg0: PreferencesHandler) -> None: ...

  def setPrintFileHandler(self, arg0: PrintFilesHandler) -> None: ...

  def setQuitHandler(self, arg0: QuitHandler) -> None: ...

  def setQuitStrategy(self, arg0: QuitStrategy) -> None: ...


class DialogPeer:

  def blockWindows(self, arg0: List[Window]) -> None: ...

  def repositionSecurityWarning(self) -> None: ...

  def setModalBlocked(self, arg0: Dialog, arg1: bool) -> None: ...

  def setOpacity(self, arg0: float) -> None: ...

  def setOpaque(self, arg0: bool) -> None: ...

  def setResizable(self, arg0: bool) -> None: ...

  def setTitle(self, arg0: str) -> None: ...

  def toBack(self) -> None: ...

  def toFront(self) -> None: ...

  def updateAlwaysOnTopState(self) -> None: ...

  def updateFocusableWindowState(self) -> None: ...

  def updateIconImages(self) -> None: ...

  def updateMinimumSize(self) -> None: ...

  def updateWindow(self) -> None: ...


class FileDialogPeer:

  def blockWindows(self, arg0: List[Window]) -> None: ...

  def setDirectory(self, arg0: str) -> None: ...

  def setFile(self, arg0: str) -> None: ...

  def setFilenameFilter(self, arg0: FilenameFilter) -> None: ...

  def setResizable(self, arg0: bool) -> None: ...

  def setTitle(self, arg0: str) -> None: ...


class FontPeer: ...


class FramePeer:

  def emulateActivation(self, arg0: bool) -> None: ...

  def getBoundsPrivate(self) -> Rectangle: ...

  def getState(self) -> int: ...

  def repositionSecurityWarning(self) -> None: ...

  def setBoundsPrivate(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...

  def setMaximizedBounds(self, arg0: Rectangle) -> None: ...

  def setMenuBar(self, arg0: MenuBar) -> None: ...

  def setModalBlocked(self, arg0: Dialog, arg1: bool) -> None: ...

  def setOpacity(self, arg0: float) -> None: ...

  def setOpaque(self, arg0: bool) -> None: ...

  def setResizable(self, arg0: bool) -> None: ...

  def setState(self, arg0: int) -> None: ...

  def setTitle(self, arg0: str) -> None: ...

  def toBack(self) -> None: ...

  def toFront(self) -> None: ...

  def updateAlwaysOnTopState(self) -> None: ...

  def updateFocusableWindowState(self) -> None: ...

  def updateIconImages(self) -> None: ...

  def updateMinimumSize(self) -> None: ...

  def updateWindow(self) -> None: ...


class LabelPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setAlignment(self, arg0: int) -> None: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setText(self, arg0: str) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class LightweightPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class ListPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def add(self, arg0: str, arg1: int) -> None: ...

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def delItems(self, arg0: int, arg1: int) -> None: ...

  def deselect(self, arg0: int) -> None: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  @overload
  def getMinimumSize(self) -> Dimension: ...

  @overload
  def getMinimumSize(self, arg0: int) -> Dimension: ...

  @overload
  def getPreferredSize(self) -> Dimension: ...

  @overload
  def getPreferredSize(self, arg0: int) -> Dimension: ...

  def getSelectedIndexes(self) -> list[int]: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def makeVisible(self, arg0: int) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def removeAll(self) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def select(self, arg0: int) -> None: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setMultipleMode(self, arg0: bool) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class MenuBarPeer:

  def addHelpMenu(self, arg0: Menu) -> None: ...

  def addMenu(self, arg0: Menu) -> None: ...

  def delMenu(self, arg0: int) -> None: ...

  def dispose(self) -> None: ...

  def setFont(self, arg0: Font) -> None: ...


class MenuComponentPeer:

  def dispose(self) -> None: ...

  def setFont(self, arg0: Font) -> None: ...


class MenuItemPeer:

  def dispose(self) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setLabel(self, arg0: str) -> None: ...


class MenuPeer:

  def addItem(self, arg0: MenuItem) -> None: ...

  def delItem(self, arg0: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setLabel(self, arg0: str) -> None: ...


class MouseInfoPeer:

  def fillPointWithCoords(self, arg0: Point) -> int: ...

  def isWindowUnderMouse(self, arg0: Window) -> bool: ...


class PanelPeer:

  def beginLayout(self) -> None: ...

  def beginValidate(self) -> None: ...

  def endLayout(self) -> None: ...

  def endValidate(self) -> None: ...

  def getInsets(self) -> Insets: ...


class PopupMenuPeer:

  def addItem(self, arg0: MenuItem) -> None: ...

  def delItem(self, arg0: int) -> None: ...

  def show(self, arg0: Event) -> None: ...


class RobotPeer:

  def getRGBPixel(self, arg0: int, arg1: int) -> int: ...

  def getRGBPixels(self, arg0: Rectangle) -> list[int]: ...

  def keyPress(self, arg0: int) -> None: ...

  def keyRelease(self, arg0: int) -> None: ...

  def mouseMove(self, arg0: int, arg1: int) -> None: ...

  def mousePress(self, arg0: int) -> None: ...

  def mouseRelease(self, arg0: int) -> None: ...

  def mouseWheel(self, arg0: int) -> None: ...

  def useAbsoluteCoordinates(self) -> bool: ...


class ScrollPanePeer:

  def beginLayout(self) -> None: ...

  def beginValidate(self) -> None: ...

  def childResized(self, arg0: int, arg1: int) -> None: ...

  def endLayout(self) -> None: ...

  def endValidate(self) -> None: ...

  def getHScrollbarHeight(self) -> int: ...

  def getInsets(self) -> Insets: ...

  def getVScrollbarWidth(self) -> int: ...

  def setScrollPosition(self, arg0: int, arg1: int) -> None: ...

  def setUnitIncrement(self, arg0: Adjustable, arg1: int) -> None: ...

  def setValue(self, arg0: Adjustable, arg1: int) -> None: ...


class ScrollbarPeer:

  DEFAULT_OPERATION: int

  NO_EMBEDDED_CHECK: int

  RESET_OPERATION: int

  SET_BOUNDS: int

  SET_CLIENT_SIZE: int

  SET_LOCATION: int

  SET_SIZE: int

  def applyShape(self, arg0: Region) -> None: ...

  def canDetermineObscurity(self) -> bool: ...

  def coalescePaintEvent(self, arg0: PaintEvent) -> None: ...

  def createBuffers(self, arg0: int, arg1: BufferCapabilities) -> None: ...

  def createImage(self, arg0: int, arg1: int) -> Image: ...

  def createVolatileImage(self, arg0: int, arg1: int) -> VolatileImage: ...

  def destroyBuffers(self) -> None: ...

  def dispose(self) -> None: ...

  def flip(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: BufferCapabilities.FlipContents) -> None: ...

  def getBackBuffer(self) -> Image: ...

  def getColorModel(self) -> ColorModel: ...

  def getFontMetrics(self, arg0: Font) -> FontMetrics: ...

  def getGraphics(self) -> Graphics: ...

  def getGraphicsConfiguration(self) -> GraphicsConfiguration: ...

  def getLocationOnScreen(self) -> Point: ...

  def getMinimumSize(self) -> Dimension: ...

  def getPreferredSize(self) -> Dimension: ...

  def handleEvent(self, arg0: AWTEvent) -> None: ...

  def handlesWheelScrolling(self) -> bool: ...

  def isFocusable(self) -> bool: ...

  def isObscured(self) -> bool: ...

  def isReparentSupported(self) -> bool: ...

  def layout(self) -> None: ...

  def paint(self, arg0: Graphics) -> None: ...

  def print(self, arg0: Graphics) -> None: ...

  def reparent(self, arg0: ContainerPeer) -> None: ...

  def requestFocus(self, arg0: Component, arg1: bool, arg2: bool, arg3: int, arg4: FocusEvent.Cause) -> bool: ...

  def setBackground(self, arg0: Color) -> None: ...

  def setBounds(self, arg0: int, arg1: int, arg2: int, arg3: int, arg4: int) -> None: ...

  def setEnabled(self, arg0: bool) -> None: ...

  def setFont(self, arg0: Font) -> None: ...

  def setForeground(self, arg0: Color) -> None: ...

  def setLineIncrement(self, arg0: int) -> None: ...

  def setPageIncrement(self, arg0: int) -> None: ...

  def setValues(self, arg0: int, arg1: int, arg2: int, arg3: int) -> None: ...

  def setVisible(self, arg0: bool) -> None: ...

  def setZOrder(self, arg0: ComponentPeer) -> None: ...

  def updateCursorImmediately(self) -> None: ...

  def updateGraphicsData(self, arg0: GraphicsConfiguration) -> bool: ...


class TaskbarPeer:

  def getIconImage(self) -> Image: ...

  def getMenu(self) -> PopupMenu: ...

  def isSupported(self, arg0: Taskbar.Feature) -> bool: ...

  def requestUserAttention(self, arg0: bool, arg1: bool) -> None: ...

  def requestWindowUserAttention(self, arg0: Window) -> None: ...

  def setIconBadge(self, arg0: str) -> None: ...

  def setIconImage(self, arg0: Image) -> None: ...

  def setMenu(self, arg0: PopupMenu) -> None: ...

  def setProgressValue(self, arg0: int) -> None: ...

  def setWindowIconBadge(self, arg0: Window, arg1: Image) -> None: ...

  def setWindowProgressState(self, arg0: Window, arg1: Taskbar.State) -> None: ...

  def setWindowProgressValue(self, arg0: Window, arg1: int) -> None: ...


class TextAreaPeer:

  def getCaretPosition(self) -> int: ...

  def getInputMethodRequests(self) -> InputMethodRequests: ...

  def getMinimumSize(self, arg0: int, arg1: int) -> Dimension: ...

  def getPreferredSize(self, arg0: int, arg1: int) -> Dimension: ...

  def getSelectionEnd(self) -> int: ...

  def getSelectionStart(self) -> int: ...

  def getText(self) -> str: ...

  def insert(self, arg0: str, arg1: int) -> None: ...

  def replaceRange(self, arg0: str, arg1: int, arg2: int) -> None: ...

  def select(self, arg0: int, arg1: int) -> None: ...

  def setCaretPosition(self, arg0: int) -> None: ...

  def setEditable(self, arg0: bool) -> None: ...

  def setText(self, arg0: str) -> None: ...


class TextFieldPeer:

  def getCaretPosition(self) -> int: ...

  def getInputMethodRequests(self) -> InputMethodRequests: ...

  def getMinimumSize(self, arg0: int) -> Dimension: ...

  def getPreferredSize(self, arg0: int) -> Dimension: ...

  def getSelectionEnd(self) -> int: ...

  def getSelectionStart(self) -> int: ...

  def getText(self) -> str: ...

  def select(self, arg0: int, arg1: int) -> None: ...

  def setCaretPosition(self, arg0: int) -> None: ...

  def setEchoChar(self, arg0: str) -> None: ...

  def setEditable(self, arg0: bool) -> None: ...

  def setText(self, arg0: str) -> None: ...


class WindowPeer:

  def beginLayout(self) -> None: ...

  def beginValidate(self) -> None: ...

  def endLayout(self) -> None: ...

  def endValidate(self) -> None: ...

  def getInsets(self) -> Insets: ...

  def repositionSecurityWarning(self) -> None: ...

  def setModalBlocked(self, arg0: Dialog, arg1: bool) -> None: ...

  def setOpacity(self, arg0: float) -> None: ...

  def setOpaque(self, arg0: bool) -> None: ...

  def toBack(self) -> None: ...

  def toFront(self) -> None: ...

  def updateAlwaysOnTopState(self) -> None: ...

  def updateFocusableWindowState(self) -> None: ...

  def updateIconImages(self) -> None: ...

  def updateMinimumSize(self) -> None: ...

  def updateWindow(self) -> None: ...

